spring:
  application:
    name: tfoodsapi
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/tfood
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
  data:
    minio:
      url: http://localhost:9000/
      access-key: minioadmin
      secret-key: minioadmin
      bucket-name: tfoodbucket

  cache:
    type: redis
security:
  jwt:
    secret: "thisisaverylongsecretkeythatneedstobesecure!"
server:
  port: 3040
redis:
  port: 6379
  host: localhost


